name: Terraform Destroy
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Init
        run: terraform init 
        #-backend-config="tfstate-bucket-61647e65" -backend-config="terraform.tfstate" -backend-config="region=us-east-1"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
